import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../src/controller.js',import.meta.url),'utf8');
const {GreenhouseController}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const defaults=()=>({temperature:25,humidity:60,soil:45,light:65,water:75,hour:14,clockValid:true});
const c=new GreenhouseController();let r=defaults();
c.sample(r);c.tick(0);assert(!c.out.pump&&!c.out.fan&&!c.out.lamp);
c.reset();r.temperature=32;c.sample(r);c.tick(0);assert(c.out.fan);
r.temperature=27;for(let i=0;i<50;i++)c.sample(r);c.tick(100);assert(c.out.fan);
r.temperature=26;for(let i=0;i<50;i++)c.sample(r);c.tick(200);assert(!c.out.fan);
c.reset();r=defaults();r.soil=25;c.sample(r);c.tick(0);assert(c.out.pump);
c.tick(5999);assert(c.out.pump);c.tick(6000);assert(!c.out.pump&&c.out.cooldown);
c.tick(17999);assert(!c.out.pump);c.tick(18000);assert(c.out.pump);
r.water=10;c.sample(r);c.tick(18001);assert(!c.out.pump&&c.out.waterLow);
c.reset();r=defaults();r.soil=25;r.water=NaN;c.sample(r);c.tick(0);assert(!c.out.pump&&c.out.sensorFault);
c.reset();r=defaults();r.light=15;c.sample(r);c.tick(0);assert(c.out.lamp);
r.hour=22;c.sample(r);c.tick(1);assert(!c.out.lamp);r.hour=6;c.sample(r);c.tick(2);assert(c.out.lamp);
r.clockValid=false;c.sample(r);c.tick(3);assert(!c.out.lamp);
c.reset();r=defaults();r.soil=25;c.sample(r);c.tick(4294967295-3000);assert(c.out.pump);c.tick(2999);assert(!c.out.pump);
c.reset();r=defaults();r.temperature=NaN;c.sample(r);c.tick(0);assert(c.out.fan&&c.out.sensorFault);
console.log('PASS: identical C++ / JavaScript acceptance scenarios');
